const express = require('express');
const userRoutes = express.Router();
const {LOGIN, REGISTER} = require('../../../utils/config/app-constants').ROUTES.USER;
const userController = require('../controllers/user');
const validateMiddleWare = require('../../../utils/middlewares/schema-validator');
const validateUser = require('../../../db/models/user-schema').validateUser;
userRoutes.post(LOGIN, userController.login);
userRoutes.post(REGISTER,[validateMiddleWare(validateUser)], userController.register);
//userRoutes.post('/update-password',[validateMiddleWare(validateUser)], userController.register);
module.exports = userRoutes;